databases:
  - name: kpoptype_DB
    databaseName: kpoptype_db
    user: kpoptype
    region: singapore

services:
  - type: web
    name: kpoptype
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kpoptype_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
